name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? Preferably via Discord
      placeholder: Nickname#1234
    validations:
      required: false

  - type: input
    id: command
    attributes:
      label: Which command did you (try to) use? (If any?)
      description: Also mention all arguments you used with the command.
      placeholder: "/command argument: 123 another_argument: text"
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see! (Preferably) Also Attach screenshots if possible
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste (or screenshot) any relevant bot response. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: markdown
  attributes:
    value: "Thank you for reporting this bug!"
