blank_issues_enabled: true
contact_links:
  - name: Security & Vulnerabilities
    about: "Please report security vulnerabilities or potential permission escalation directly to me over discord: Mmesek#2901."
